name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: bjia56/setup-cosmocc@main
      with:
        version: "latest"
        
    - name: gcc make
      run: make

    - name: cosmocc
      env:
          FEATURES: cli
          CC: cosmocc -mclang
          CXX: cosmoc++
          PLATFORM: cosmo
      run: make

