name: Cosmo Releaser

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: bjia56/setup-cosmocc@main
      with:
        version: "latest"
    - name: make
      run: make
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            build/dhtd
        tag_name: ${{ github.ref_name }}
        release_name: dhtd_cosmopolitan
        draft: false
        prerelease: false
        overwrite: true   
